apiVersion: v1
kind: ConfigMap
metadata:
  name: fleet-server-config
  namespace: elk
data:
  FLEET_SERVER_ENABLE: "true"
  FLEET_SERVER_SERVICE_TOKEN: "AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL2ZsZWV0LXNlcnZlci10b2tlbjpHSFBicUxiTFFtU1JoaUdhOXFqWWhn"
  FLEET_SERVER_ELASTICSEARCH_HOST: "http://elasticsearch-service.elk.svc:9200"
  FLEET_SERVER_POLICY_ID: "fleet-server-policy"  # Create this policy in Kibana Fleet settings
  KIBANA_HOST: "http://kibana-service:5601"
  KIBANA_SERVICE_TOKEN: "AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS10b2tlbjowdFlSS3g5OFMyU2NYbjRTZEpLdFd3"
  FLEET_SERVER_PORT: "8220"  # Use only the port number here













