apiVersion: v1
kind: ConfigMap
metadata:
  name: fleet-server-config
  namespace: elk
data:
  FLEET_SERVER_ENABLE: "true"
  FLEET_SERVER_SERVICE_TOKEN: "AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE3MjQ1OTY1OTUxNzk6bHdLakdLaWVTZ2lra0M3bFFXTWdKZw"
  FLEET_SERVER_ELASTICSEARCH_HOST: "http://elasticsearch-service:9200"
  FLEET_SERVER_POLICY_ID: "fleet-server-policy"  # Create this policy in Kibana Fleet settings
  KIBANA_HOST: "http://kibana-service:5601"
  KIBANA_SERVICE_TOKEN: "AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS10b2tlbjpQeDNKblJEZFNlS3JkZ3VSVjE1NjVn"
  FLEET_SERVER_PORT: "8220"  # Use only the port number here
