apiVersion: v1
kind: ConfigMap
metadata:
  name: fleet-server-config
  namespace: elk
data:
  FLEET_SERVER_ENABLE: "true"
  FLEET_SERVER_SERVICE_TOKEN: "AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE3MjQ3ODM4ODg1NzY6aU5SejRtV2RTM3lOZDFGaF8yZ3RFUQ"
  FLEET_SERVER_ELASTICSEARCH_HOST: "http://elasticsearch-service.elk.svc:9200"
  FLEET_SERVER_POLICY_ID: "ff135bea-450c-479e-8a41-5295c0d7a1aa"  # Create this policy in Kibana Fleet settings
  KIBANA_HOST: "http://kibana-service.elk.svc:5601"
  KIBANA_SERVICE_TOKEN: "AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS10b2tlbjp6Y0p4eDkyMVI2ZS10c293TG5NWkpR"
  FLEET_SERVER_PORT: "8220"  # Use only the port number here
















