apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-server
  namespace: elk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleet-server
  template:
    metadata:
      labels:
        app: fleet-server
    spec:
      containers:
        - name: fleet-server
          image: docker.elastic.co/beats/elastic-agent:8.14.3
          envFrom:
            - configMapRef:
                name: fleet-server-config  # Reference to the ConfigMap defined below
          ports:
            - containerPort: 8220
              name: fleet
