apiVersion: v1
kind: Service
metadata:
  name: kibana-service
  namespace: elk
  labels:
    app: kibana
spec:
  ports:
    - port: 5601
      targetPort: 5601
      protocol: TCP
  selector:
    app: kibana
  type: LoadBalancer
