apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: elk
data:
  kibana.yml: |
    server.name: kibana
    server.host: "0.0.0.0"
    elasticsearch.hosts: ["http://elasticsearch-service:9200"]
    monitoring.ui.container.elasticsearch.enabled: true
    elasticsearch.serviceAccountToken: "AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS10b2tlbjpQeDNKblJEZFNlS3JkZ3VSVjE1NjVn"
    xpack.monitoring.enabled: true
    xpack.security.encryptionKey: "lsDKt1BJ8LJhdscNlGHkzHVlR7JzkZ7F"
    xpack.reporting.encryptionKey: "VxDs6xHYT38jv6Zp9kHrGf9JwN8KL9SK"
    xpack.encryptedSavedObjects.encryptionKey: "YkHt2KvZ5P3lGnL8lFgH8sKl4RnL9N7S"

