apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: elk
data:
  kibana.yml: |
    server.name: kibana
    server.host: "0.0.0.0"
    elasticsearch.hosts: ["http://elasticsearch-service.elk.svc:9200"]
    monitoring.ui.container.elasticsearch.enabled: true
    elasticsearch.serviceAccountToken: "AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS10b2tlbjp6Y0p4eDkyMVI2ZS10c293TG5NWkpR"
    xpack.monitoring.enabled: true
    xpack.security.encryptionKey: "lsDKt1BJ8LJhdscNlGHkzHVlR7JzkZ7F"
    xpack.reporting.encryptionKey: "VxDs6xHYT38jv6Zp9kHrGf9JwN8KL9SK"
    xpack.encryptedSavedObjects.encryptionKey: "YkHt2KvZ5P3lGnL8lFgH8sKl4RnL9N7S"
    xpack.fleet.agents.enabled: true
    xpack.fleet.agents.fleet_server.hosts: ["https://fleet-server.elk.svc:8220"]
    xpack.fleet.agents.elasticsearch.hosts: ["http://elasticsearch-service.elk.svc:9200"]
    xpack.fleet.packages:
      - name: system
        version: latest
      - name: elastic_agent
        version: latest
    xpack.fleet.agentPolicies:
      - name: Fleet Server Policy
        id: fleet-server-policy
        namespace: default
        monitoring_enabled:
          - logs
          - metrics
        package_policies:
          - package:
              name: system
            name: System Integration 1
            id: preconfigured-system-1
            inputs:
              system-system/metrics:
                enabled: true
                vars:
                  '[system.hostfs]': home/test
                streams:
                  '[system.core]':
                    enabled: true
                    vars:
                      period: 20s
              system-winlog:
                enabled: false
















