apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: elk
data:
  logstash.conf: |
    input {
      stdin {}
    }
    output {
      elasticsearch {
        hosts => ["http://elasticsearch-service:9200"]
        index => "logs-%{+YYYY.MM.dd}"
        user => "elastic"
        password => "elasticelastic"
      }
    }
  logstash.yml: |
    http.host: "0.0.0.0"
    xpack.monitoring.enabled: true
    xpack.monitoring.elasticsearch.hosts: ["http://elasticsearch-service:9200"]
    xpack.monitoring.elasticsearch.username: "elastic"
    xpack.monitoring.elasticsearch.password: "elasticelastic"
