apiVersion: v1
kind: Service
metadata:
  name: logstash-service
  namespace: elk
spec:
  type: LoadBalancer
  selector:
    app: logstash
  ports:
    - port: 5044
      targetPort: 5044
      protocol: TCP
      name: tcp
