apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
  namespace: elk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
        - name: ubuntu
          image: ubuntu:20.04
          command: ["sleep", "infinity"]
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
